version: "3.8"

services:
  xray:
    image: teddysun/xray:latest
    container_name: xray-proxy
    restart: unless-stopped
    ports:
      - "8001:8001" # VMess WebSocket Google
      - "8002:8002" # VMess WebSocket Cloudflare
      - "8003:8003" # VLESS WebSocket Microsoft
      - "8004:8004" # VLESS WebSocket Google
      - "8005:8005" # Trojan WebSocket
      - "8006:8006" # VLESS WebSocket Cloudflare
      - "8007:8007" # VLESS WebSocket GitHub
      - "8080:8080" # VLESS Direct TCP (replaced VMess)
    volumes:
      - ./xray-config.json:/etc/xray/config.json:ro
      - ./logs:/var/log/xray
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy-network
    command: ["xray", "run", "-config", "/etc/xray/config.json"]

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SERVERURL=94.130.107.116
      - SERVERPORT=51820
      - PEERS=client1,client2,client3,client4,client5
      - PEERDNS=8.8.8.8,1.1.1.1
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=true
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp" # WireGuard UDP port
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - proxy-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-updater
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
