services:
  - type: web
    name: v2ray-proxy
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: PORT
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1
